Основная часть задания 3
alx-t/react-store pull request #2
Opened 2018-11-15 04:58 UTC by alx-t

Без DnD

2018-11-15 06:50 UTC, index01d requested changes

2018-11-15 06:50 UTC, index01d commented on src/components/CatalogPage.js
> +    this.state = { cart: new ShoppingCart() };
я не рекомендую выделять класс-некомпонент в таких случаях. Лучше содержать в состоянии готовый массив продуктов в корзине. Чтобы избежать несвязанного кода в классе компонента-каталога нужно создать компонент-контейнер корзины (CartContainer), реализовать изменение состояния и методы там, после чего обернуть CatalogPage в CartContainer (`<CartContainer><CatalogPage /></CartContainer>`)

2018-11-15 06:50 UTC, index01d commented on src/components/widgets/catalog/ProductCard.js
> +            <BuyButton item={{ id, title, price }} />
или целиком product?

2018-11-15 06:50 UTC, index01d commented on src/components/CatalogPage.js
> +      <cartContext.Provider value={{ cart: this.state.cart, event: this.addItemClick }}>
event слишком общее название для ключа с методом, полагаю лучше addToCart

2018-11-15 06:50 UTC, index01d commented on src/components/widgets/catalog/elements/Counter.js
> +      ({ cart, event }) => (
event не используется, но зачем-то деструктурируется

2018-11-15 06:50 UTC, index01d commented on src/components/widgets/catalog/elements/Counter.js
> +import cart_icon from '~/src/images/cart.png';
лучше записывать идентификаторы camelCase'ом

2018-11-15 08:47 UTC, alx-t commented on src/components/widgets/catalog/elements/Counter.js
> +import cart_icon from '~/src/images/cart.png';
Пардон, привычка

2018-11-15 08:47 UTC, alx-t commented on src/components/widgets/catalog/elements/Counter.js
> +      ({ cart, event }) => (
уже используется в ДнД )) недоглядел

2018-11-15 09:00 UTC, alx-t commented on src/components/widgets/catalog/ProductCard.js
> +            <BuyButton item={{ id, title, price }} />
исправил

2018-11-15 09:00 UTC, alx-t commented on src/components/CatalogPage.js
> +      <cartContext.Provider value={{ cart: this.state.cart, event: this.addItemClick }}>
исправил

2018-11-15 09:45 UTC, alx-t commented on src/components/CatalogPage.js
> +    this.state = { cart: new ShoppingCart() };
Извини, не оч понял (( можешь пояснить почему и может есть пример? если я делаю CartContainer получается LineItem мне тоже нужно переделать в компонент-контейнер? но для LineItem мне нечего рендерить, или функционал LineItem перенести в компонент Корзины? но тогда получается Корзина перегружена работой со строками заказа ((

2018-11-16 06:56 UTC, index01d requested changes

2018-11-16 06:56 UTC, index01d commented on src/components/CatalogPage.js
> +      <cartContext.Provider value={{ cart: this.state.cart, eventAddToCart: this.addItemClick }}>
префикс event выглядит избыточным :)

2018-11-16 06:56 UTC, index01d commented on src/components/CatalogPage.js
> +    this.state = { cart: new ShoppingCart() };
LineItem будет помещен не в презентационный компонент корзины, а в контейнерный компонент CartContainer. Давай попробуем начать это изменение и по ходу дела я уже скорректирую

2018-11-16 07:01 UTC, index01d commented on src/components/CatalogPage.js
> +    this.state = { cart: new ShoppingCart() };
ответ на почему: 
1) в состоянии мы оперируем объектами, а не экземплярами класса. 
2) оставаясь в рамках концепции контейнерных и презентационных компонентов мы сможем продолжить пользоваться инструментами для обработки изменений данных из экосистемы реакт, вместо того, чтобы самостоятельно обрабатывать изменения
3) чуть позже обработка данных будет производиться в еще более функциональном стиле и модельная логика в ООП-стиле будет нам мешать
P.S.: это не значит что модельная логика в ООП-стиле совсем плоха и не годится, но нужно иметь массу оснований, чтобы завести её в React-приложении (это чуть позже кристализуется по ходу занятий)

2018-11-17 07:14 UTC, index01d requested changes

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +        <CatalogPage />
следовало передать как children

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +  children: PropTypes.instanceOf(CatalogPage)
любой компонент

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +import CatalogPage from '../CatalogPage';
импортировать не нужно

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +        <CatalogPage />
здесь оставить `{this.props.children}`

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +    const newItems = this.state.items;
`= this.state.items.concat(li)`

2018-11-17 07:14 UTC, index01d commented on src/components/containers/ShoppingCart.js
> +    newItems.push(li);
push здесь использовать не следует, тк иначе ты на месте меняешь содержимое this.state.items без вызова setState, что может привести к неприятным побочным эффектам

2018-11-17 10:11 UTC, index01d approved these changes

2018-11-17 10:14 UTC, merged