Основная часть задания
alx-t/react-store pull request #3
Opened 2018-11-21 10:46 UTC by alx-t

2018-11-23 16:39 UTC, index01d requested changes

2018-11-23 16:39 UTC, index01d commented on src/App.js
> +            <Menu secondary>
меню необходимо декомпозировать в отдельный компонент (пример в практике давался упрощенно)

2018-11-23 16:39 UTC, index01d commented on src/App.js
> +                active={activeItem === 'main'}
не совсем понятно: зачем потребовался в этом кейсе active с состоянием? вроде как пути достаточно

2018-11-23 16:39 UTC, index01d commented on src/components/views/ProductPage.js
> +      id: this.props.id,
в состояние не следует копировать данные, которые можно получить из свойств (см первое занятие)

2018-11-23 16:39 UTC, index01d commented on src/components/widgets/catalog/ProductCard.js
>      this.state = { product: this.props.product }
в состояние не следует копировать данные, которые можно получить из свойств (см первое занятие)

2018-11-26 09:10 UTC, alx-t commented on src/App.js
> +                active={activeItem === 'main'}
только для красоты )) типа выделенный пункт меню подсвечивается, уберу сейчас

2018-11-26 11:41 UTC, index01d approved these changes

2018-11-26 12:09 UTC, merged