Добавил Redux в проект
alx-t/react-store pull request #7
Opened 2018-12-06 19:17 UTC by alx-t

2018-12-07 09:13 UTC, index01d requested changes

2018-12-07 09:13 UTC, index01d commented on index.html
> +    <div id="devtools"></div>
можно также взглянуть на https://github.com/zalmoxisus/redux-devtools-extension как вариант (в занятии не упомянуто, но по факту очень удобный заменитель)

2018-12-07 09:13 UTC, index01d commented on package.json
> +    "containers": "0.0.1",
?

2018-12-07 09:13 UTC, index01d commented on package.json
> +    "store": "^2.0.12",
?

2018-12-07 09:13 UTC, index01d commented on src/actions/Cart.js
> +export function viewCart() {
не используется?

2018-12-07 09:13 UTC, index01d commented on src/reducers/index.js
> +  routing: routerReducer
не вполне ясно зачем потребовался react-router-redux

2018-12-07 09:13 UTC, index01d commented on src/components/widgets/catalog/elements/Cart.js
> +    this.props.addItem({ 'id': id, 'title': title, 'quantity': 1, 'price': price });
`addItem({ id, title, quantity: 1, price })`

2018-12-07 09:13 UTC, index01d commented on src/components/widgets/catalog/elements/Cart.js
> +import { connect } from 'react-redux';
лучше выделить Cart/Cart.js с презентационным компонентом и Cart/index.js с контейнерной частью (connect и его аргументы)

2018-12-07 09:13 UTC, index01d commented on src/components/widgets/catalog/Catalog.js
> +    if (this.state.visible && state && state.message) {
location.state лучше именовать почетче (e.g.: location.state), чтобы код был понятнее

2018-12-07 09:13 UTC, index01d commented on src/components/widgets/catalog/Catalog.js
>      const { products } = this.props;
лучше деструктурировать здесь location

2018-12-07 09:13 UTC, index01d commented on src/components/views/ProductPage.js
> +    fetchProduct(this.props.id);
к следующему занятию стоит также вынести фетчинг из componentDidMount в роуты (пример с prepareData)

2018-12-07 09:22 UTC, alx-t commented on index.html
> +    <div id="devtools"></div>
спасибо, 1 глазом смотрел, но не пробовал

2018-12-07 09:29 UTC, alx-t commented on src/reducers/index.js
> +  routing: routerReducer
тут и выше - не все ладилось, пробовал разное, мусор постарался убрать потом, но что-то пропустил ((

2018-12-08 15:10 UTC, index01d requested changes
1) нужно убрать ненужные неиспользуемые action'ы из контейнеров
2) src/images нужно утащить или в public/images или наоборот поближе к компоненту использования (в директорию компонента)
3) Стоит создать директории views/ProductPage (унести туда сам компонент представления, ProductDetail) и  views/Catalog (унести туда все специфичные для страницы компоненты widgets/catalog и сам компонент представления)

2018-12-08 15:10 UTC, index01d commented on src/App.js
> +function historyCb(location, action = 'PUSS') {
PUSH :)

2018-12-08 15:10 UTC, index01d commented on src/App.js
> +let history = createBrowserHistory();
стоит вынести в helpers/history, как и historyCb (просится облегчить App.js)

2018-12-11 06:09 UTC, index01d approved these changes

2018-12-12 12:04 UTC, merged