Основная часть задания 8
alx-t/react-store pull request #9
Opened 2018-12-19 13:24 UTC by alx-t

2018-12-20 07:16 UTC, index01d requested changes

2018-12-20 07:16 UTC, index01d commented on src/actions/Order.js
> +      query: {order: order},
`{ order }`

2018-12-20 07:16 UTC, index01d commented on src/components/views/OrderPage/Order.js
> +        {isSuccess && (<Redirect to={{
должно быть реализовано с помощью history.push в onSubmit в контейнере формы.

2018-12-20 07:16 UTC, index01d commented on src/components/views/OrderPage/index.js
> +  onSubmit: (values, dispatch) => dispatch(sendOrder(values))
здесь можно подписаться на результат выполнения dispatch и в случае успеха выполнить history.push

2018-12-20 07:19 UTC, alx-t commented on src/components/views/OrderPage/Order.js
> +        {isSuccess && (<Redirect to={{
сделаю, а почему? мне для общего понимания ))

2018-12-21 07:50 UTC, index01d commented on src/components/views/OrderPage/Order.js
> +        {isSuccess && (<Redirect to={{
потому что переход в случае успешной отправки это часть процесса обработки отправки, а здесь код представления формы

2018-12-22 17:17 UTC, index01d approved these changes

2018-12-22 17:17 UTC, index01d commented on src/components/views/OrderPage/index.js
> +          throw new SubmissionError({ message: 'Send Order failed!' });
лучше бы конечно еще попробовать отработать ошибки в конкретных полях

2018-12-24 14:18 UTC, merged